inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'vendor/**/*'
    - 'spec/decidim_dummy_app/db/**.rb'
    - 'spec/decidim_dummy_app/db/**/**.rb'
    - 'spec/decidim_dummy_app/config/**/**.rb'
    - 'development_app/db/**/*.rb'
    - 'development_app/Gemfile'
    - 'development_app/config/**/*.rb'
