name: "[ci] Test"

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

env:
  RUBY_VERSION: 3.2.8
  NODE_VERSION: 18.17.1
  OMNIAUTH_ODOO_KEYCLOAK_CLIENT_ID: ExampleClientId

jobs:
  test-report:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install GraphicsMagick
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf imagemagick

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Setup Database
        run: bundle exec rake test_app
   
      - run: RAILS_ENV=test bundle exec rails assets:precompile
        name: Precompile assets
        working-directory: ./spec/decidim_dummy_app/

      - run: bundle exec rspec
        name: RSpec
        env:
          CODECOV: 1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore
